export const ActionTypes = {
  GET_BRANDS: "GET_BRANDS",
  SELECTED_BRAND: "SELECTED_BRAND",
  REMOVE_SELECTED_BRAND: "REMOVE_SELECTED_BRAND",

  GET_SELECTED_PRODUCT: "GET_SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",

  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
  SIGNOUT_SUCCESS: "SIGNOUT_SUCCESS",

  GET_CART: "GET_CART",
  CLEAR_CART: "CLEAR_CART",
  GET_ADDRESSES: "GET_ADDRESSES",
};
